### PR TITLE
Feature/fix mint lpt

### PR DESCRIPTION
**Pull request by taiki1frsh**
Issue: #456 , #392

The purpose of this PR is mostly on #456. 
Please refer there.

### CODE REVIEW

**Comment by KimuraYu45z** [comment]
I think this conflicts with
https://github.com/UnUniFi/chain/pull/458

**Comment by taiki1frsh** [comment]
> I think this conflicts with #458

yeah, at #444 , there are conflicts. I fix them there.

**Comment by taiki1frsh** [comment]
resolved conflicts regarding lpt functions.

**Comment by KimuraYu45z** [comment]
close #392 
close #456

**Review by KimuraYu45z — APPROVED** [review]

**Review by KimuraYu45z — APPROVED** [review]

**Pull request merged**
