### PR TITLE
Spec of frontend-incentive module

### PR DESCRIPTION
**Pull request by taiki1frsy**
This PR is for the peer review of the design of the `frontend-incentive` module.
The peer review guide is here: https://www.notion.so/cauchye/00e95ed9b2cf4648863309bcbd788f10
Please ignore the commits and edited files irrelevant to the `frontend-incentive` module.

### CODE REVIEW

**Comment by mkXultra** [comment]
I think Better to separate ADR from Spec.

**Comment by mkXultra** [comment]
Isn't State a data structure to be stored in DB?

**Comment by mkXultra** [comment]
Is `Frontend Register` necessary?
https://github.com/UnUniFi/chain/blob/design/spec/x/frontend-incentive/spec/03_messages.md

**Comment by mkXultra** [comment]
The module should check at the state of the Tx when it succeeds and when it fails

**Comment by mkXultra** [comment]
check memo size

**Comment by taiki1frsy** [comment]
@mkXultra 
I separated the docs for adr folder and modified&added descriptions you mentioned.
Please review for them.

**Comment by taiki1frsy** [comment]
> I think Better to separate ADR from Spec.
Created architecture folder under doc and moved requirement, term_list and check_list docs.

> Isn't State a data structure to be stored in DB?
Modified the contents of 02_state.md.

> Is `Frontend Register` necessary? https://github.com/UnUniFi/chain/blob/design/spec/x/frontend-incentive/spec/03_messages.md

I, at the moment, adopted the style that frontend registration for the complicated weights setting and  memo field usage is for the equal distribution.

> The module should check at the state of the Tx when it succeeds and when it fails

Mentioned here: https://github.com/UnUniFi/chain/blob/af837d776b085c4986bbc360a85917d90890a571/docs/architecture/adr-frontend-incentive.md?plain=1#L100
https://github.com/UnUniFi/chain/blob/af837d776b085c4986bbc360a85917d90890a571/docs/architecture/adr-frontend-incentive.md?plain=1#L120

**Comment by mkXultra** [comment]
@taiki1frsy 
How do we use this module?
We also need documentation on the integration

**Review by mkXultra — APPROVED** [review]

**Pull request merged**
